### ISSUE TITLE
Buildwheel does not automatically install pyyaml

### ISSUE THREAD

**Issue by AJR07** [CeltiumCDev/PyDClass#6]
After running the command to pip install from this github repository, I encountered this error:
```

> pydclass
Traceback (most recent call last):
  File "/Users/angjunray/.pyenv/versions/3.10.4/bin/pydclass", line 7, in <module>
    import pydclass.gen_img
  File "/Users/angjunray/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pydclass/gen_img.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
I believe it is because the library ```pyyaml``` was not included in the build wheel.

**Comment by VitriSnake** [comment]
OK! Thank you for your report!
I'll fix that right now, you can now install it!
Sorry for my late reply ;)
